YZune/CourseAdapter

- src/main/java/parser/JNUParser.kt
- src/main/java/test/JNUTest.kt
暨大的解析教务系统的课程表，可能解析一些比较特殊的课程名会出现错误......还没有实际试验过能不能直接用在教务系统上orz，原本想试试但是尝试了很多方法愣是不能在程序里正常加载出完整的网页源码 o(╥﹏╥)o 就先这样吧 orz
暨大的教务系统网址：jwxt.jnu.edu.cn
> 暨南大学教务系统课程解析

- .idea/inspectionProfiles/Project_Default.xml
- .idea/misc.xml
- src/parser/ECJTUParser.kt
- src/test/ECJTUTest.kt
> try to adapt ECJTU

- src/main/java/bean/Course.kt
- src/main/java/parser/SITParser.kt
> 适配SIT上海应用技术大学，增加了一些注释

- src/main/java/parser/SITParser.kt
修复了上应大SIT部分课表只存在一节课时发生的错位bug …
> 修复了上应大SIT部分课表只存在一节课时发生的错位bug

- .idea/misc.xml
- src/main/java/Common.kt
- src/main/java/parser/AHNUParser.kt
- src/main/java/test/AHNUTest.kt
> 适配了AHNU安徽师范大学的课表解析

- src/main/java/parser/SYSUParser.kt
Signed-off-by: Qjbtiger <Qjb8668@gmail.com>
> 修复了一个导入时顺序错乱的bug

- src/main/java/Common.kt
- src/main/java/parser/GZHUYJSParser.kt
- src/main/java/test/GZHUYJSTest.kt
> 适配广州大学研究生系统

- src/main/java/parser/GDBYXYParser.kt
> add 广东白云学院青果教务系统

- src/main/java/parser/GDBYXYParser.kt
> change 缩短了广东白云学院课程表地点，变成"楼-教室号"

- src/main/java/parser/NFUParser.kt
> 修复 中山大学南方学院 单双周及空地点导入失败bug

- src/main/java/parser/ECUPLParser.kt
- src/main/java/test/ECUPLTest.kt
> Add ECUPL parser (华东政法大学)

- src/main/java/Common.kt
- src/main/java/parser/ZjvtitParser.kt
- src/main/java/test/ZjvtitTest.kt
> add ztvtit

- src/main/java/parser/ZjvtitParser.kt
- src/main/java/test/ZjvtitTest.kt
> 浙江交通职业技术学院

- src/main/java/parser/BJTUParser.kt
- 获取课程名由原来的正则表达式换成了indexof+slice的形式 
如果还是出现问题大大可以截一下Null出现的时候tempEach的值嘛，我会尽力修改parser的
大大辛苦了，要注意休息鸭
(｡･∀･)ﾉﾞ
> refactor:修改了获取课程名称的方法

- .idea/misc.xml
- src/main/java/parser/HNZJParser.java
- src/main/java/test/HNZJTest.java
> 河南职业技术学院教务解析

- src/main/java/parser/SUSTechParser.kt
- src/main/java/test/SUSTechTest.kt
> Support SUSTech

- src/main/java/Common.kt
- src/main/java/Generator.kt
- src/main/java/bean/CourseBaseBean.kt
- src/main/java/parser/HUSTParser.kt
- src/main/java/parser/Parser.kt
- src/main/java/parser/ZjvtitParser.kt
- src/main/java/test/HUSTTest.kt
支持链接 http://hub.m.hust.edu.cn/kcb/index.jsp#kclist_section?kcname=&lsname=
新增 课表文件生成器，运行自定义Parser后可直接导入至WakeUp
> 支持 华中科技大学 微校园 课表

- .idea/codeStyles/Project.xml
- src/main/java/parser/JXAUJkParser.kt
- src/main/java/parser/JXAUParser.kt
- src/main/java/test/JXAUJkTest.kt
- src/main/java/test/JXAUTest.kt
> 添加江西农业大学支持

- src/main/java/parser/HrbeuGraduateParser.kt
- src/main/java/test/HRBEUTest.kt
> 增加哈工程研究生院课表解析

- src/main/java/parser/NYISTParser.kt
- src/main/java/test/NYISTTest.kt
导入网址：https://app3.nyist.edu.cn/ui/#/courseTable
> 新增南阳理工学院课程导入

- src/main/java/parser/HrbeuGraduateParser.kt
哈工程研究生课表，由于没有班级信息，室友错上了一节别班的课，因此增加班级信息和注释，避免此类情况再次发生
> 哈工程研究生课表，增加班级信息和注释

- src/main/java/parser/HUNNUParser.kt
从教务系统解析需要在多个页面获取参数，进行多次跳转，相关的WebViewClient和JavascriptInterface代码已在注释中给出进行参考，使用它们才能跳转到具有课程信息的界面
在webView中教务系统的页面不能正确的加载，但是使用这个跳转的方法能够正常解析，可提示用户登录后无视页面效果导入即可
> 湖南师范大学适配：更改解析逻辑：直接从教务系统解析；新增学分解析；

- src/main/java/parser/AHSTUParser.kt
- src/main/java/test/AHSTUTest.kt
获取课程表html的方法在AHSTUCourseProvider 类中，有详细使用步骤，具体使用步骤查看AHSTUTest,kt内的getCourseHTML函数
> 适配[安徽科技学院](http://www.ahstu.edu.cn/)

- src/main/java/parser/SHTechParser.kt
- src/main/java/parser/XJTUGraduateParser.kt
- src/main/java/test/XJTUTest.kt
对西安交通大学研究生课程表导入进行了适配，但由于本人是第一次写Kotlin程序，可能不太好。这个代码在本地测试时，是可以通过的。
> 对西安交通大学研究生课程导入进行了适配

- src/main/java/parser/HUATParser.java
- src/main/java/test/HUATTest.java
- 修复某处数组溢出错误的 bug
- 重写课程信息读取逻辑，简化操作
- 简化变量名
- 完善残缺内容课程情况判断
> Weeks array boundary bug fix

- src/main/java/parser/SHTechParser.kt
1.上海科技大学研究生教务更新了框架结构,解析器进行了适应化更新.
2.原教务系统在多位教授合作授课的情况下产生的bug已不再出现,移除了这部分处理代码.
3.修复了其他bug.
4.更新了导入说明.
> 上海科技大学研究生教务导入2023春学期更新

- src/main/java/parser/AHSTUParser.kt
添加: 上课时间表
修复: 服务器可能出现`请不要过快点击`导致无法获取请求课表的参数的错误
> 修复安徽科技学院导入课程出错

- src/main/java/parser/SUESParser.kt
Reverts YZune/CourseAdapter#76
> Revert "[fix]SUESParser: 小问题修复"

- src/main/java/parser/SUESParser2.kt
在获取总周数失败时默认设置为30周。
过滤掉*~~可爱的教务老师操作失误添加的本不应存在的~~*地点为空的课程。
> [fix]SUESParser2: 小问题更正

- src/main/java/parser/SIMCParser.kt
- src/main/java/test/SIMCTest.kt
上海市高级技工学校（上海工程技术大学高等职业技术学院）教学服务平台
学校官网：[http://www.sts.edu.cn/](http://www.sts.edu.cn/) [https://www.simc.cn/](https://www.simc.cn/) [http://gz.sues.edu.cn/](http://gz.sues.edu.cn/)
教务地址：[http://jxfw.simc.cn/fwpt/login.action](http://jxfw.simc.cn/fwpt/login.action) （内网系统）
> [add]上海市高级技工学校教学服务平台

- src/main/java/parser/SWJTUGraduateParser.kt
- src/main/java/test/SWJTUTest.kt
> 增加了对西南交通大学研究生课表的支持

- src/main/java/parser/BFAforYJSParser.kt
- src/main/java/test/BFAforYJSTest.kt
> 初步适配北京电影学院-研究生教育管理系统，经在IDEA中测试，对于课表界面的HTML文件能够正常解析并提取课程信息

- src/main/java/parser/XAUATParser.java
- src/main/java/test/XAUATTest.java
上一版的程序在解析课程时可能造成课程丢失，进行修复；
优化上课地点显示的长度，包括雁塔和草堂；
覆写Parser类的public方法
> 修复并优化西安建筑科技大学研究生教务

- .gitignore
- src/main/java/parser/USTCGraduateParser.kt
- src/main/java/test/USTCGraduateTest.kt
虽有“学在科大”app，但它的重心并不在课表上. 故在此试作适配，并已在 **较为多样** 的场景下测试通过.
> 适配 #中国科学技术大学研究生

- src/main/java/parser/HHUParser.kt
- src/main/java/test/HHUTest.kt
旧的那个教务系统（新URP系统）已经废弃了，麻烦删除一下，感谢
只适用于本科生课程
> 适配河海大学新教务系统

- src/main/java/parser/NWPUGraduateParser.kt
适配教务系统的时间格式更改
>目前教务系统表示上课节数由原先的纯`上1` `晚1` 一类变为混合着纯数字的格式（如`10`）
没注意到教务系统有更新，怪罪到app上了，红豆泥非常抱歉
> fix: 西北工业大学研究生教务

- .idea/.gitignore
- src/main/java/parser/BUAAParser.kt
> refactor: 优化 北京航空航天大学-json 解析方式为正则表达式

- src/main/java/parser/HrbeuGraduateParser.kt
> 教务系统更新，重新适配

- .idea/material_theme_project_new.xml
- .idea/misc.xml
- LICENSE
- src/main/java/parser/SYSUParser2024.kt
- src/main/java/test/SYSUTest2024.kt
> 中山大学课程表导入2024版

- src/main/java/parser/SHTechParser2024.kt
- src/main/java/test/SHTechTest2024.kt
> feat: 上海科技大学教务课程2024导入

- src/main/java/parser/SHUParser2024.kt
- src/main/java/test/SHUTest2024.kt
新系统的手机版ui为卡片，电脑版ui为表格，原先仅仅适配了手机版ui
> fix: 修复了手机页面无法导入的bug

- src/main/java/parser/SHUParser2024.kt
- src/main/java/test/SHUTest2024.kt
- 修复了解析单独一周或不连续周数课程时变为连续周数课程的bug（例如1,6周上课的课程会被解析为1-6周上课）
- 移除了未使用的变量
- 移除了测试文件中的 html 文件路径
- 部分代码格式化
> fix: 修复了解析单独一周或不连续周数课程时变为连续周数课程的bug

- .idea/libraries/com_google_code_gson_gson_2_8_6.xml
- .idea/misc.xml
- src/main/java/parser/CTGUParser.kt
- src/main/java/test/CTGUTEST.kt
> 三峡大学研究生课表适配

- src/main/java/parser/GXICParser.kt
- src/main/java/test/GXICTest.kt
> 适配：广西工业职业技术学院教务系统（内网）

- src/main/java/parser/LNGDParser.kt
- src/main/java/test/LNGDTest.kt
> 辽宁轨道交通职业学院的课表适配，原来那个用不了

- src/main/java/Common.kt
- src/main/java/parser/WISTParser.kt
- src/main/java/test/WISTTest.kt
- 新增 WISTParser 解析器，支持武汉船舶职业技术学院课表 HTML 格式
- 支持“中1”“中2”节次解析
- 支持混合格式周次解析与课程合并优化逻辑
> 修正了Wist parser解析器

- src/main/java/parser/JAVTCParser.kt
- src/main/java/test/JAVTCTest.kt
我需要在他登录完成后请求http://223.84.63.131:99/jiaowu/JWXS/pkgl/XsKB_List.aspx获取课表，因为我们学校用的是老强智不会显示课表菜单，我第一次写这个，不知道是不是这样写，要是不对，告诉我如何修改
> 江西航空职业技术学院 Parser
